# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(942, 739)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(5, 0, 931, 681))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.andBt = QtWidgets.QToolButton(self.frame)
        self.andBt.setGeometry(QtCore.QRect(830, 50, 41, 31))
        self.andBt.setObjectName("andBt")
        self.orBt = QtWidgets.QToolButton(self.frame)
        self.orBt.setGeometry(QtCore.QRect(830, 10, 41, 31))
        self.orBt.setStyleSheet("")
        self.orBt.setObjectName("orBt")
        self.eventBt = QtWidgets.QToolButton(self.frame)
        self.eventBt.setGeometry(QtCore.QRect(830, 90, 41, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("state.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eventBt.setIcon(icon)
        self.eventBt.setIconSize(QtCore.QSize(30, 30))
        self.eventBt.setObjectName("eventBt")
        self.cursorBt = QtWidgets.QToolButton(self.frame)
        self.cursorBt.setGeometry(QtCore.QRect(830, 210, 41, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("cursor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cursorBt.setIcon(icon1)
        self.cursorBt.setIconSize(QtCore.QSize(41, 31))
        self.cursorBt.setObjectName("cursorBt")
        self.iniEventBt = QtWidgets.QToolButton(self.frame)
        self.iniEventBt.setGeometry(QtCore.QRect(830, 130, 41, 31))
        self.iniEventBt.setIconSize(QtCore.QSize(30, 30))
        self.iniEventBt.setObjectName("iniEventBt")
        self.dangEventBt = QtWidgets.QToolButton(self.frame)
        self.dangEventBt.setGeometry(QtCore.QRect(830, 170, 41, 31))
        self.dangEventBt.setIconSize(QtCore.QSize(30, 30))
        self.dangEventBt.setObjectName("dangEventBt")
        self.connectBt = QtWidgets.QToolButton(self.frame)
        self.connectBt.setGeometry(QtCore.QRect(830, 250, 41, 31))
        self.connectBt.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("connect.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connectBt.setIcon(icon2)
        self.connectBt.setIconSize(QtCore.QSize(30, 30))
        self.connectBt.setObjectName("connectBt")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox.setGeometry(QtCore.QRect(860, 310, 62, 22))
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.probLabel = QtWidgets.QLabel(self.frame)
        self.probLabel.setGeometry(QtCore.QRect(780, 310, 81, 21))
        self.probLabel.setObjectName("probLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 942, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ЛВМ"))
        self.andBt.setText(_translate("MainWindow", "AND"))
        self.orBt.setText(_translate("MainWindow", "OR"))
        self.eventBt.setToolTip(_translate("MainWindow", "Промежуточное событие"))
        self.eventBt.setText(_translate("MainWindow", "..."))
        self.cursorBt.setText(_translate("MainWindow", "..."))
        self.iniEventBt.setToolTip(_translate("MainWindow", "Инициирующее событие"))
        self.iniEventBt.setText(_translate("MainWindow", "ИС"))
        self.dangEventBt.setToolTip(_translate("MainWindow", "Опасное событие"))
        self.dangEventBt.setText(_translate("MainWindow", "ОС"))
        self.connectBt.setToolTip(_translate("MainWindow", "Соединение событий"))
        self.probLabel.setText(_translate("MainWindow", "Вероятность"))
